---
nginx_expires: "1h"
nginx_port: "80"
nginx_sites: []
nginx_enabled_sites: []
nginx_disabled_sites:
  - default
nginx_development_environment: false
nginx_snippet_files: []

nginx_ckan_port: 8080

nginx_service_state: started

nginx_domain: ""
nginx_secondary_domain: ""

nginx_content_security_policy_script_domains:
  - "platform.twitter.com"
  - "syndication.twitter.com"
  - "cdn.syndication.twimg.com"
  - "*.disqus.com"
  - "https://disqus.com"
  - "*.disquscdn.com"
  - "https://www.google.com/recaptcha/"
  - "https://www.gstatic.com/"
  - "https://www.google.com"
  - "cdn.matomo.cloud"
  - "suomi.matomo.cloud"

nginx_content_security_policy_style_domains:
  - "https://fonts.googleapis.com"
  - "https://platform.twitter.com"
  - "https://ton.twimg.com"
  - "*.disquscdn.com"
  - "https://www.google.com"
  - "https://ajax.googleapis.com"
  - "https://www.gstatic.com"

nginx_content_security_policy_frame_domains:
  - "{% if nginx_domain is defined and nginx_domain != ''%}*.{{ nginx_domain }} {% endif %}"
  - "{% if nginx_secondary_domain is defined and nginx_secondary_domain != '' %}*.{{ nginx_secondary_domain}} {% endif %}"
  - "syndication.twitter.com"
  - "https://platform.twitter.com"
  - "https://disqus.com"
  - "*.disqus.com"
  - "https://www.google.com/recaptcha/"

nginx_content_security_policy_default_domains:
  - "*.disquscdn.com"
  - "https://disqus.com"

nginx_content_security_policy:
  - "default-src 'self' {{ nginx_content_security_policy_default_domains | join (' ') }};"
  - "script-src 'self' 'unsafe-inline' 'unsafe-eval' {{ nginx_content_security_policy_script_domains | join(' ') }};"
  - "img-src 'self' https: gravatar.com data:;"
  - "style-src 'self' 'unsafe-inline' {{ nginx_content_security_policy_style_domains | join(' ') }};"
  - "font-src 'self' https://themes.googleusercontent.com https://fonts.gstatic.com;"
  - "frame-src 'self' {{ nginx_content_security_policy_frame_domains | join(' ') }};"
  - "object-src 'none';"
  - "connect-src 'self' https://links.services.disqus.com wss://realtime.services.disqus.com https://epsg.io *;"
