version: "2"

# NOTE: ports are open for dev purposes
# NOTE: /opt/drupal/web structure:
# - /var/www/html/modules
# - /var/www/html/profiles
# - /var/www/html/themes
# - /var/www/html/sites
# NOTE: drupal holds control over its volumes and populates them
#       nginx just mounts the volumes to specific paths as read-only

services:
  postgres:
    build:
      context: ./docker/postgres
    restart: on-failure
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      - PGDATA=/var/lib/postgresql/data/db
      - POSTGRES_DB=${DB_CKAN}
      - POSTGRES_USER=${DB_CKAN_USER}
      - POSTGRES_PASSWORD=${DB_CKAN_PASS}
      - DB_DATASTORE_READONLY=${DB_DATASTORE_READONLY}
      - DB_DATASTORE_READONLY_USER=${DB_DATASTORE_READONLY_USER}
      - DB_DATASTORE_READONLY_PASS=${DB_DATASTORE_READONLY_PASS}
      - DB_DRUPAL=${DB_DRUPAL}
      - DB_DRUPAL_USER=${DB_DRUPAL_USER}
      - DB_DRUPAL_PASS=${DB_DRUPAL_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_CKAN_USER}"]

  redis:
    image: redis:6.0.7
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - backend

  solr:
    build:
      context: ./docker/solr
    restart: on-failure
    expose:
      - 8983
    networks:
      - backend
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data

  ckan:
    build:
      context: ./
      dockerfile: docker/ckan/Dockerfile
    restart: always
    networks:
      - frontend
      - backend
    depends_on:
      - postgres
      - redis
      - solr
    ports:
      - "5000:5000"
    env_file:
      - ./docker/.env.ckan.local
    environment:
      - CKAN_HOST=${CKAN_HOST}
      - CKAN_PORT=${CKAN_PORT}
      - DATAPUSHER_HOST=${DATAPUSHER_HOST}
      - DATAPUSHER_PORT=${DATAPUSHER_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - SOLR_HOST=${SOLR_HOST}
      - SOLR_PORT=${SOLR_PORT}
      - SOLR_PATH=${SOLR_PATH}
      - DB_HOST=${DB_HOST}
      - DB_CKAN=${DB_CKAN}
      - DB_CKAN_USER=${DB_CKAN_USER}
      - DB_CKAN_PASS=${DB_CKAN_PASS}
      - DB_DATASTORE_READONLY=${DB_DATASTORE_READONLY}
      - DB_DATASTORE_READONLY_USER=${DB_DATASTORE_READONLY_USER}
      - DB_DATASTORE_READONLY_PASS=${DB_DATASTORE_READONLY_PASS}
      - DB_DRUPAL=${DB_DRUPAL}
      - DB_DRUPAL_USER=${DB_DRUPAL_USER}
      - DB_DRUPAL_PASS=${DB_DRUPAL_PASS}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - SECONDARY_DOMAIN_NAME=${SECONDARY_DOMAIN_NAME}
      - SITE_PROTOCOL=${SITE_PROTOCOL}
      - ROLES_CKAN_ADMIN=${ROLES_CKAN_ADMIN}
      - SYSADMIN_USER=${SYSADMIN_USER}
      - SYSADMIN_PASS=${SYSADMIN_PASS}
      - SYSADMIN_EMAIL=${SYSADMIN_EMAIL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_TO=${SMTP_TO}
      - SMTP_FROM_ERROR=${SMTP_FROM_ERROR}
      - SMTP_TO_ERROR=${SMTP_TO_ERROR}
      - SMTP_PROTOCOL=${SMTP_PROTOCOL}
      - SMTP_PORT=${SMTP_PORT}
      - MATOMO_ENABLED=${MATOMO_ENABLED}
      - MATOMO_SITE_ID=${MATOMO_SITE_ID}
      - MATOMO_DOMAIN=${MATOMO_DOMAIN}
      - MATOMO_SCRIPT_DOMAIN=${MATOMO_SCRIPT_DOMAIN}
      - MATOMO_TOKEN=${MATOMO_TOKEN}
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - DISQUS_DOMAIN=${DISQUS_DOMAIN}
      - SENTRY_DSN=${SENTRY_DSN}
      - SENTRY_ENV=${SENTRY_ENV}
      - CKAN_SQLALCHEMY_URL=postgresql://${DB_CKAN_USER}:${DB_CKAN_PASS}@${DB_HOST}/${DB_CKAN}
      - CKAN_DATASTORE_WRITE_URL=postgresql://${DB_CKAN_USER}:${DB_CKAN_PASS}@${DB_HOST}/${DB_DATASTORE_READONLY}
      - CKAN_DATASTORE_READ_URL=postgresql://${DB_DATASTORE_READONLY_USER}:${DB_DATASTORE_READONLY_PASS}@${DB_HOST}/${DB_DATASTORE_READONLY}
      - CKAN_SOLR_URL=http://${SOLR_HOST}:${SOLR_PORT}/${SOLR_PATH}
      - CKAN_SYSADMIN_NAME=${SYSADMIN_USER}
      - CKAN_SYSADMIN_PASSWORD=${SYSADMIN_PASS}
      - CKAN_SYSADMIN_EMAIL=${SYSADMIN_EMAIL}
    volumes:
      - ckan_data:/srv/app/data
      - ckan_resources:/var/www/resources

  datapusher:
    build:
      context: ./docker/datapusher
    restart: always
    networks:
      - frontend
      - backend
    expose:
      - 8000
    env_file:
      - ./docker/.env.datapusher.local
    environment:
      - DATAPUSHER_REWRITE_URL=http://${CKAN_HOST}:${CKAN_PORT}/data

  drupal:
    build:
      context: ./
      dockerfile: docker/drupal/Dockerfile
    restart: always
    networks:
      - frontend
      - backend
    depends_on:
      - postgres
    expose:
      - 9000
    env_file:
      - ./docker/.env.drupal.local
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DRUPAL=${DB_DRUPAL}
      - DB_DRUPAL_USER=${DB_DRUPAL_USER}
      - DB_DRUPAL_PASS=${DB_DRUPAL_PASS}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - SECONDARY_DOMAIN_NAME=${SECONDARY_DOMAIN_NAME}
      - SITE_NAME=${SITE_NAME}
      - ROLES_CKAN_ADMIN=${ROLES_CKAN_ADMIN}
      - ROLES_EDITOR=${ROLES_EDITOR}
      - ROLES_PUBLISHER=${ROLES_PUBLISHER}
      - SYSADMIN_USER=${SYSADMIN_USER}
      - SYSADMIN_PASS=${SYSADMIN_PASS}
      - SYSADMIN_EMAIL=${SYSADMIN_EMAIL}
      - SYSADMIN_ROLES=${SYSADMIN_ROLES}
      - NGINX_HOST=${NGINX_HOST}
      - CKAN_HOST=${CKAN_HOST}
      - CKAN_PORT=${CKAN_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_PROTOCOL=${SMTP_PROTOCOL}
      - SMTP_PORT=${SMTP_PORT}
      - MATOMO_ENABLED=${MATOMO_ENABLED}
      - MATOMO_SITE_ID=${MATOMO_SITE_ID}
      - MATOMO_DOMAIN=${MATOMO_DOMAIN}
      - MATOMO_SCRIPT_DOMAIN=${MATOMO_SCRIPT_DOMAIN}
      - MATOMO_TOKEN=${MATOMO_TOKEN}
      - USERS_0_USER=${USERS_0_USER}
      - USERS_0_PASS=${USERS_0_PASS}
      - USERS_0_EMAIL=${USERS_0_EMAIL}
      - USERS_0_ROLES=${USERS_0_ROLES}
      - USERS_1_USER=${USERS_1_USER}
      - USERS_1_PASS=${USERS_1_PASS}
      - USERS_1_EMAIL=${USERS_1_EMAIL}
      - USERS_1_ROLES=${USERS_1_ROLES}
      - USERS_2_USER=${USERS_2_USER}
      - USERS_2_PASS=${USERS_2_PASS}
      - USERS_2_EMAIL=${USERS_2_EMAIL}
    volumes:
      - drupal_data:/opt/drupal/web
      - drupal_resources:/var/www/resources

  nginx:
    build:
      context: ./docker/nginx
    restart: always
    networks:
      - frontend
    depends_on:
      - ckan
      - drupal
    ports:
      - "80:80"
    env_file:
      - ./docker/.env.nginx.local
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - NAMESERVER=${NAMESERVER}
      - CKAN_HOST=${CKAN_HOST}
      - CKAN_PORT=${CKAN_PORT}
      - DRUPAL_HOST=${DRUPAL_HOST}
      - DRUPAL_PORT=${DRUPAL_PORT}
    volumes:
      - drupal_data:/var/www/html:ro
      - ckan_resources:/var/www/ckan_resources:ro
      - drupal_resources:/var/www/drupal_resources:ro

  mailhog:
    image: mailhog/mailhog:latest
    restart: on-failure
    networks:
      - frontend
      - backend
    expose:
      - 1025
    ports:
      - "8025:8025"
    environment:
      - MH_HOSTNAME=${SMTP_HOST}
      - MH_STORAGE=memory
      - MH_AUTH_FILE=/mailhog/auth
    volumes:
      - ./docker/.mh-auth:/mailhog/auth

volumes:
  postgres_data:
  solr_data:
  ckan_data:
  drupal_data:
  ckan_resources:
  drupal_resources:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
