---

- name: Create SSL path
  file:
    path: "{{ certificates_path }}"
    state: directory
    mode: "0755"
    owner: root
    group: "{{ www_group }}"
  tags:
    - nginx
    - ssl

- name: Check for pre-generated SSL certificate
  stat:
    path: "{{ ssl_path }}/{{ ssl_crt_primary }}"
  register: ssl_cert_file
  when: ssl_path != false

- name: Generate self-signed SSL certificate
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN={{ hostname }}" -days 3650 -keyout "{{ ssl_path }}/{{ ssl_key_primary }}" -out "{{ ssl_path }}/{{ ssl_crt_primary }}" -extensions v3_ca creates="{{ ssl_path }}/{{ ssl_crt_primary }}"
  register: generate_certificates
  when: ssl_path != false and not ssl_cert_file.stat.exists
  tags:
    - nginx
    - ssl

- name: Copy SSL files
  copy:
    src: "{{ ssl_path }}/{{ item }}"
    dest: "{{ certificates_path }}/{{ item }}"
    owner: root
    group: "{{ www_group }}"
    mode: "0640"
    remote_src: yes
  when: ssl_path != false
  with_items:
    - "{{ ssl_crt_primary }}"
    - "{{ ssl_crt_secondary }}"
    - "{{ ssl_key_primary }}"
    - "{{ ssl_key_secondary }}"
  tags:
    - nginx
    - ssl

- name: Ensure certificates ownership
  shell: chmod 640 {{ certificates_path }}/* && chown "root:{{ www_group }}" {{ certificates_path }}/*
  when: ssl_path == false and generate_certificates|changed
  tags:
    - nginx
    - ssl
