---


- name: Install polib
  pip:
    name: polib
    virtualenv: "{{ virtual_environment }}"
    state: latest
  tags:
  - translations
  - ckan
  - translation_table


- name: Compile extension translations
  command: "{{ virtual_environment }}/bin/python setup.py compile_catalog -f"
  with_items: "{{ extensions_with_translations }}"
  args:
    chdir: "{{ ckanext_sync_path }}/{{ item }}"
  tags:
    - translations


- name: Add facet translations
  command: /usr/lib/ckan/default/bin/paster --plugin=ckanext-ytp_main ytp-facet-translations "{{ server_path }}/ckanext-ytp_main/ckanext/ytp/i18n" -c /etc/ckan/default/production.ini
  tags:
  - translations
  - ckan
