---
# defaults file for opendata_frontend
opendata_frontend_packages:
  - libjpeg-turbo8
  - nodejs

opendata_frontend_modules_path: "../modules"

opendata_frontend_server_path: "/root/ytp"
opendata_frontend_cache_path: "/srv/ytp"

opendata_frontend_deployment_environment_id: ""
opendata_frontend_copy_secret_npmrc: false
