---

- name: Reread supervisor
  shell: supervisorctl reread
  when: supervisor_configuration is changed
  tags:
  - ckan

- name: Ensure supervisor services
  shell: supervisorctl add {{ item }}
  when: supervisor_configuration is changed
  with_flattened:
    - "{{ supervisor_services }}"
  tags:
  - ckan

- name: Ensure supervisor services are restarted
  supervisorctl:
    name: "{{ item }}"
    state: restarted
  with_flattened:
    - "{{ supervisor_services }}"
  tags:
  - ckan

- name: Ensure harvester cron job
  cron:
    name: "harvest"
    minute: "*/5"
    hour: "22-23,0-2"
    job: "{{ virtual_environment }}/bin/paster --plugin=ckanext-harvest harvester run --config={{ ckan_ini }}"
  tags:
  - ckan
  - cron

- name: Ensure tracking cron job
  cron:
    name: "tracking"
    minute: "0"
    hour: "22"
    job: "{{ virtual_environment }}/bin/paster --plugin=ckan tracking update --config={{ ckan_ini }} && {{ virtual_environment }}/bin/paster --plugin=ckan search-index rebuild -r --config={{ ckan_ini }}"
  tags:
  - ckan
  - cron

- name: Ensure qa cron job
  cron:
    name: "qa"
    minute: "0"
    hour: "2"
    job: "{{ virtual_environment }}/bin/paster --plugin=ckanext-qa qa update --config={{ ckan_ini }}"
  when: "'qa' in ckan_extensions"
  tags:
  - ckan
  - cron

- name: Remove qa cron job if qa not enabled
  cron:
    name: "qa"
    state: "absent"
  when: "'qa' not in ckan_extensions"

- name: Ensure report cron job
  cron:
    name: "report"
    minute: "0"
    hour: "3"
    job: "{{ virtual_environment }}/bin/paster --plugin=ckanext-report report generate --config={{ ckan_ini }}"
  tags:
  - ckan
  - cron

- name: Reindex
  shell: touch "{{ files_root }}/.solr-reindex" && ./bin/paster --plugin=ckan  search-index rebuild --config="{{ ckan_ini }}" chdir="{{ virtual_environment }}" creates="{{ files_root }}/.solr-reindex"
  when: Reindex == true
  async: 1200
  poll: "{{ 0 if Reindex == true else 10 }}"
  tags:
  - ckan
  - non-local
  - test

- name: Add email reminder about expiring datasets as a cron job
  cron:
    name: "Add email reminder"
    minute: "0"
    hour: "9"
    job: "{{ virtual_environment }}/bin/paster --plugin=ckanext-reminder reminder send --config={{ ckan_ini }}"
  tags:
  - ckan
  - cron
