---

drupal_site_name: avoindata.fi
drupal_root: "{{ www_root }}/{{ drupal_name }}"

drupal_theme_path: "{{ drupal_root }}/sites/all/themes"
features_module_path: "{{ drupal_root }}/sites/all/modules/ytp_features"

bootstrap_version: "3.3.4"

drupal_files_path: "{{ files_root }}/drupal"

extracted_features:
  - language_feature
  - article_feature
  - service_alert_feature
  - article_view_feature
  - blocks_feature
  - frontpage_tutorial
  - calendar_feature
  - feature_blocks_feature

ytp_features_path: "../modules/ytp-drupal-features"

translation_cache_path: "{{ cache_path }}/translations"
translation_languages:
  - "fi"
  - "sv"
translation_projects:
  - "ytp-theme-drupal"
  - "ytp-assets-common"
translation_text_groups:
  - "field"
  - "node"

enable_email_verification: False
drupal_error_level: "2"
