---

- name: Configure logrotation for CKAN
  copy:
    dest: /etc/logrotate.d/ckan
    content: "{{ ckan_logrotate_conf }}"
    mode: 0644
    owner: root
    group: root

- name: Setup CKAN configuration files
  template:
    src: "{{ item.template }}"
    dest: "{{ item.file }}"
    mode: "0640"
    owner: root
    group: "{{ ckan_www_group }}"
  with_items: "{{ ckan_config_files }}"
  notify: Restart CKAN

- name: Setup WSGI configuration files
  template:
    src: "{{ item.template }}"
    dest: "{{ item.file }}"
    mode: "0640"
    owner: root
    group: "{{ ckan_www_group }}"
  with_items: "{{ wsgi_config_files }}"
  notify: Restart CKAN

- name: Setup beaker session cleanup script
  template:
    src: "beaker_session_cleanup.sh.j2"
    dest: "/usr/local/sbin/beaker_session_cleanup.sh"
    mode: "0500"
    owner: root
    group: "root"

# Background services can block database update
- name: Stop supervisor services
  command: supervisorctl stop all
  tags:
    - skip_ansible_lint
    - supervisor

- name: re-minify CKAN javascript files
  shell: ./bin/ckan --config {{ ckan_ini }} minify {{ ckan_source_path }}/ckan/public/base/javascript  chdir="{{ ckan_virtual_environment }}"
  tags:
    - skip_ansible_lint

- include: database.yml

- name: Execute SQL files
  shell: set -o pipefail; cat /{{ ckan_cache_path }}/{{ item }} | psql --set ON_ERROR_STOP=1
  args:
    executable: "/bin/bash"
  become_user: postgres
  become: true
  with_items: "{{ ckan_sql_files_to_execute }}"
  when: ckan_postgres_installed_locally

- name: Execute SQL files
  shell: >-
    set -o pipefail; cat /{{ ckan_cache_path }}/{{ item }} |
    psql -d datastore_default -h "{{ ckan_postgres.server.host }}" -U "{{ ckan_postgres_admin_user }}"
    --set ON_ERROR_STOP=1
  args:
    executable: "/bin/bash"
  with_items: "{{ ckan_sql_files_to_execute }}"
  environment:
    PGPASSWORD: "{{ ckan_postgres_admin_password }}"
  when: not ckan_postgres_installed_locally

- name: Add facet translations
  command: >-
    {{ ckan_virtual_environment }}/bin/ckan
    -c {{ ckan_ini }}
    opendata add-facet-translations "{{ ckan_server_path }}/ckanext-ytp_main/ckanext/ytp/i18n"
  tags:
    - skip_ansible_lint

- name: Create platform vocabulary
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config '{{ item.file }}'
    sixodp-showcase create_platform_vocabulary
  with_items: "{{ ckan_config_files }}"
  tags:
    - skip_ansible_lint

- name: Create showcase_type vocabulary
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config '{{ item.file }}'
    sixodp-showcase create_showcase_type_vocabulary
  with_items: "{{ ckan_config_files }}"
  tags:
    - skip_ansible_lint

- name: Copy supervisor configuration
  template:
    src: "supervisor.conf.j2"
    dest: "/etc/supervisor/conf.d/ytp.conf"
    mode: "0644"
    owner: root
    group: root
  register: supervisor_configuration
  notify:
    - Restart supervisor services
  tags:
    - supervisor

- name: Ensure supervisor services
  supervisorctl:
    name: "{{ item }}"
    state: present
  with_flattened:
    - "{{ ckan_supervisor_services }}"
  tags:
    - supervisor

- include: cron.yml
  tags:
    - cron
