---
- name: Add analytics fetching to cron
  cron:
    name: "analytics"
    minute: "0"
    hour: "1"
    job: >-
      {{ ckan_virtual_environment }}/bin/paster
      --plugin=ckanext-googleanalytics googleanalytics loadanalytics {{ ckan_cache_path }}/token.dat
      --config={{ ckan_ini }}
  when: ckan_google_analytics

- name: Ensure harvester cron job
  cron:
    name: "harvest"
    minute: "*/5"
    hour: "22-23,0-2"
    job: "{{ ckan_virtual_environment }}/bin/paster --plugin=ckanext-harvest harvester run --config={{ ckan_ini }}"

- name: Ensure tracking cron job
  cron:
    name: "tracking"
    minute: "0"
    hour: "22"
    job: >-
      {{ ckan_virtual_environment }}/bin/paster
      --plugin=ckan tracking update
      --config={{ ckan_ini }}
      &&
      {{ ckan_virtual_environment }}/bin/paster
      --plugin=ckan search-index rebuild -r
      --config={{ ckan_ini }}

- name: Ensure qa cron job
  cron:
    name: "qa"
    minute: "0"
    hour: "2"
    job: "{{ ckan_virtual_environment }}/bin/paster --plugin=ckanext-qa qa update --config={{ ckan_ini }}"
  when: "'qa' in ckan_extensions"

- name: Remove qa cron job if qa not enabled
  cron:
    name: "qa"
    state: "absent"
  when: "'qa' not in ckan_extensions"

- name: Ensure report cron job
  cron:
    name: "report"
    minute: "0"
    hour: "3"
    job: "{{ ckan_virtual_environment }}/bin/paster --plugin=ckanext-report report generate --config={{ ckan_ini }}"

- name: Add email reminder about expiring datasets as a cron job
  cron:
    name: "Add email reminder"
    minute: "0"
    hour: "9"
    job: "{{ ckan_virtual_environment }}/bin/paster --plugin=ckanext-reminder reminder send --config={{ ckan_ini }}"

- name: Send reminder about expiring datasets as a cron job
  cron:
    name: "Send expiring reminder"
    minute: "0"
    hour: "10"
    job: "{{ ckan_virtual_environment }}/bin/paster --plugin=ckanext-reminder reminder notify-expiry --config={{ ckan_ini }}"
