---

- name: Initialize CKAN database
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config '{{ item.file }}'
    db init
    chdir='{{ ckan_virtual_environment }}'
  with_items: "{{ ckan_config_files }}"
  tags:
    - skip_ansible_lint

- name: Upgrade CKAN database
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config {{ ckan_ini }}
    db upgrade
  tags:
    - skip_ansible_lint

- name: List existing CKAN users
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config {{ ckan_ini }}
    user list
    chdir={{ ckan_virtual_environment }}
  register: ckan_current_users
  environment:
    PYTHONIOENCODING: 'utf_8'
  tags:
    - skip_ansible_lint

- name: Create initial CKAN users
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config {{ ckan_ini }}
    user add "{{ item.username }}" "password={{ item.password }}" "email={{ item.email }}"
    chdir={{ ckan_virtual_environment }}
  ignore_errors: true
  with_flattened:
    - "{{ ckan_admin }}"
  when: item.username not in ckan_current_users.stdout
  tags:
    - skip_ansible_lint

- name: List existing CKAN admins
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config {{ ckan_ini }}
    sysadmin list
    chdir={{ ckan_virtual_environment }}
  register: ckan_current_sysadmins
  environment:
    PYTHONIOENCODING: 'utf_8'
  tags:
    - skip_ansible_lint

- name: Add CKAN sysadmins
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config '{{ ckan_ini }}'
    sysadmin add "{{ item }}"
    chdir='{{ ckan_virtual_environment }}'
  ignore_errors: true
  with_items: "{{ ckan_admins }}"
  when: item not in ckan_current_sysadmins.stdout | replace('Sysadmins', '')
  tags:
    - skip_ansible_lint

- name: Initialize request database
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config '{{ item.file }}'
    opendata-request init-db
    chdir='{{ ckan_virtual_environment }}'
  with_items: "{{ ckan_config_files }}"
  tags:
    - skip_ansible_lint

- name: Initialize Harvester database
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config '{{ item.file }}'
    harvester initdb
    chdir='{{ ckan_virtual_environment }}'
  with_items: "{{ ckan_config_files }}"
  tags:
    - skip_ansible_lint

- name: Initialize spatial database
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config '{{ item.file }}'
    spatial initdb
    chdir='{{ ckan_virtual_environment }}'
  with_items: "{{ ckan_config_files }}"
  tags:
    - skip_ansible_lint

- name: Initialize archiver database
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config '{{ item.file }}'
    archiver init
    chdir='{{ ckan_virtual_environment }}'
  with_items: "{{ ckan_config_files }}"
  when: "'ckanext-archiver' in ckan_extensions"
  tags:
    - skip_ansible_lint

- name: Initialize QA database
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config '{{ item.file }}'
    qa init
    chdir='{{ ckan_virtual_environment }}'
  with_items: "{{ ckan_config_files }}"
  when: "'ckanext-qa' in ckan_extensions"
  tags:
    - skip_ansible_lint

- name: Initialize report database
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config '{{ item.file }}'
    report initdb
    chdir='{{ ckan_virtual_environment }}'
  with_items: "{{ ckan_config_files }}"
  tags:
    - skip_ansible_lint

- name: Initialize matomo database
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config '{{ item.file }}'
    matomo init_db
    chdir='{{ ckan_virtual_environment }}'
  with_items: "{{ ckan_config_files }}"
  when: ckan_matomo_analytics
  tags:
    - skip_ansible_lint

- name: Initialize cloudstorage database
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config '{{ ckan_ini }}'
    cloudstorage initdb
    chdir='{{ ckan_virtual_environment }}'
  when: ckan_enable_cloudstorage
  tags:
    - skip_ansible_lint

- name: Initialize rating database
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config '{{ item.file }}'
    rating init
    chdir='{{ ckan_virtual_environment }}'
  with_items: "{{ ckan_config_files }}"
  when: "'ckanext-rating' in ckan_extensions"
  tags:
    - skip_ansible_lint

- name: Initialize subscription database
  shell: >-
    {{ ckan_virtual_environment }}/bin/ckan
    --config '{{ item.file }}'
    reminder initdb
    chdir='{{ ckan_virtual_environment }}'
  with_items: "{{ ckan_config_files }}"
  tags:
    - skip_ansible_lint

- name: Initialize recommendations database
  shell: >-
    {{ ckan_virtual_environment }}/bin/paster
    --plugin=ckanext-ytp_recommendation recommendation init
    --config='{{ item.file }}'
    chdir='{{ ckan_virtual_environment }}'
  with_items: "{{ ckan_config_files }}"
  tags:
    - skip_ansible_lint
