---
- name: Install virtualenv
  apt:
    package: virtualenv
    state: present

- name: Install setuptools
  apt:
    name: python-setuptools
    state: present

- name: Upgrade pip packages
  pip:
    name:
      #- pip
      - setuptools==44.1.0
      #- boto
    virtualenv: "{{ ckan_virtual_environment }}"
    state: present
  tags:
    - skip_ansible_lint
