---

- name: Create translation cache path
  file: path="{{ translation_cache_path }}" state=directory
  tags:
  - translations
  - ckan

- name: Copy CKAN translations
  copy: src="i18n/{{ item }}/LC_MESSAGES/ckan.po" dest="{{ translation_cache_path }}/ckan-{{ ckan_version }}.{{ item }}.po"
  register: ckan_translations
  with_items: translation_languages
  tags:
  - translations
  - ckan

- name: Copy CKAN Extension translations
  copy: src="{{ item[0] }}/i18n/{{ item[1] }}/LC_MESSAGES/{{ item[0] }}.po" dest="{{ translation_cache_path }}/{{ item[0] }}.{{ item[1] }}.po"
  with_nested:
    - translated_extensions
    - translation_languages
  when: ckan_translations|changed or modules_copy|changed
  tags:
    - translations
    - ckan

- name: Create temporary translation files
  command: cp "{{ translation_cache_path }}/ckan-{{ ckan_version }}.{{ item }}.po" "{{ translation_cache_path }}/ckan.{{ item }}.temporary.po"
  with_items: translation_languages
  when: ckan_translations|changed or modules_copy|changed
  tags:
  - translations
  - ckan

- name: Join translation source files
  command: msgcat "{{ cache_path }}/{{ item[0] }}/i18n/{{ item[1] }}/LC_MESSAGES/{{ item[0] }}.po" "{{ translation_cache_path }}/ckan.{{ item[1] }}.temporary.po" --use-first -o "{{ translation_cache_path }}/ckan.{{ item[1] }}.temporary.po"
  with_nested:
    - translation_projects
    - translation_languages
  when: ckan_translations|changed or modules_copy|changed
  tags:
  - translations
  - ckan

- name: Join extension translations to source files
  command: msgcat "{{ translation_cache_path }}/{{ item[0] }}.{{ item[1] }}.po" "{{ translation_cache_path }}/ckan.{{ item[1] }}.temporary.po" --use-first -o "{{ translation_cache_path }}/ckan.{{ item[1] }}.temporary.po"
  with_nested:
    - translated_extensions
    - translation_languages
  when: ckan_translations|changed or modules_copy|changed
  tags:
  - translations
  - ckan


- name: Overwrite translation files
  command: cp "{{ translation_cache_path }}/ckan.{{ item }}.temporary.po" "{{ virtual_environment }}/src/ckan/ckan/i18n/{{ item }}/LC_MESSAGES/ckan.po"
  with_items: translation_languages
  when: ckan_translations|changed or modules_copy|changed
  tags:
  - translations
  - ckan

- name: Compile translation files
  command: msgfmt "{{ virtual_environment }}/src/ckan/ckan/i18n/{{ item }}/LC_MESSAGES/ckan.po" -o "{{ virtual_environment }}/src/ckan/ckan/i18n/{{ item }}/LC_MESSAGES/ckan.mo"
  with_items: translation_languages
  when: ckan_translations|changed or modules_copy|changed
  tags:
  - translations
  - ckan
  notify: Restart Apache

- name: Add facet translations
  command: /usr/lib/ckan/default/bin/paster --plugin=ckanext-ytp-main ytp-facet-translations "{{ cache_path }}/ckanext-ytp-main/i18n" -c /etc/ckan/default/production.ini
  when: modules_copy|changed
  tags:
  - translations
  - ckan

- name: Generate Javascript translation files
  shell: ./bin/paster --plugin=ckan trans js "--config={{ ckan_ini }}" chdir="{{ virtual_environment }}"
  tags:
  - ckan
  - translations

- name: Install polib
  apt: pkg="python-polib" state=latest
  tags:
  - translations
  - ckan
  - translation_table

- name: Create translation page
  script: translation_table.py "{{ cache_path }}" "{{ www_root }}/resources/translation-table.html" "{{ virtual_environment }}/src/ckan/ckan/i18n/!LANGUAGE!/LC_MESSAGES/ckan.po" "{{ cache_path }}/translations/ckan-2.2.!LANGUAGE!.po" "fi,sv"
  tags:
  - translations
  - ckan
  - translation_table

