- name: Download Datapusher
  git:
    repo: https://github.com/6aika/datapusher.git
    dest: "{{ cache_path }}/datapusher.git"
    bare: yes

- name: Install Datapusher
  pip: name="git+file://{{ cache_path }}/datapusher.git@master#egg=datapusher" virtualenv={{ datapusherenv }} extra_args="--exists-action=s -e"

- name: Install Datapusher requirements
  pip: requirements={{ datapusherenv }}/src/datapusher/requirements.txt virtualenv={{ datapusherenv }} state=latest

- name: Link datapusher sources
  command: "{{ datapusherenv }}/bin/python setup.py develop chdir={{ datapusherenv }}/src/datapusher"

- name: Copy Datapusher site file
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner={{ item.owner }} group={{ item.group }}
  with_items:
      - { src: datapusher.j2, dest: /etc/apache2/sites-available/datapusher.conf, mode: "0644", owner: root, group: root}
      - { src: datapusher.wsgi.j2, dest: /etc/ckan/default/datapusher.wsgi, mode: "0640", owner: root, group: "{{ www_group }}" }
      - { src: datapusher_settings.py.j2, dest: /etc/ckan/default/datapusher_settings.py, mode: "0640", owner: root, group: "{{ www_group }}" }

- name: Enable Datapusher configuration
  file: src=/etc/apache2/sites-available/datapusher.conf dest=/etc/apache2/sites-enabled/datapusher.conf state=link owner=root group=root

- name: Restart Apache
  service: name=apache2 state=restarted
