---

database_ip_range: 127.0.0.1/32
database_host: localhost
database_port: 5432

ckan_database_name: ckan_default
ckan_database_username: ckan_default
ckan_database_password: pass
ckan_database_host: "{{ database_host }}"

drupal_database_name: drupal
drupal_database_username: drupal
drupal_database_password: drupal  

www_root: /var/www
www_user: www-data
www_group: www-data

drupal_name: ytp

server_path: /srv/ytp
cache_path: "{{ server_path }}/cache"
backup_path: "{{ server_path }}/backup"
scripts_path: "{{ server_path }}/scripts"
log_path: /var/log/ckan
static_path: "{{ www_root }}/static"

files_root: "{{ server_path }}/files"

all_paths:
  - "{{ server_path }}"
  - "{{ cache_path }}"
  - "{{ backup_path }}"
  - "{{ scripts_path }}"
  - "{{ log_path }}"
  - "{{ static_path }}"

drupal_admin_username: admin
drupal_admin_password: admin
drupal_admin_email: vagrant@localhost

drupal_hostname: "{{ inventory_hostname }}"

drupal_editor_rolename: editor
drupal_default_editor_username: test-editor
drupal_default_editor_email: editor@localhost
drupal_default_editor_password: test-editor-password

drupal_ckan_admin_rolename: ckan_admin

secondary_hostname: 127.0.0.1
secondary_hostname_language: en

ckan_ini: /etc/ckan/default/production.ini
virtual_environment: /usr/lib/ckan/default

harvest_username: harvest
harvest_password: harvest
harvest_email: harvest@localhost

harvest_sources: false

ckan_version: "2.2"

email_domain: "localhost"
email_domain_access: "localhost"
email_from: "no-reply@{{ email_domain }}"
error_email_from: "error@{{ email_domain }}"

admin_email: vagrant@localhost
error_email: "{{Â admin_email }}"
