---


solr_host: "{{ database_host }}"
solr_port: "8983"

redis_hostname: "{{ database_host }}"
redis_port: "6379"


ckan_test_database: { 'name': "ckan_test", 'username': "{{ ckan_database_username }}" }




www_root: /var/www
www_user: www-data
www_group: www-data



server_path: /srv/ytp
cache_path: "{{ server_path }}/cache"
backup_path: "{{ server_path }}/backup"
scripts_path: "{{ server_path }}/scripts"
log_path: /var/log/ckan
static_path: "{{ www_root }}/static"

resource_cache_path: "{{ server_path }}/resource_cache"

files_root: "{{ server_path }}/files"

all_paths:
  - "{{ server_path }}"
  - "{{ cache_path }}"
  - "{{ backup_path }}"
  - "{{ scripts_path }}"
  - "{{ log_path }}"
  - "{{ static_path }}"

hostname: 10.10.10.10
hostname_language: fi
secondary_hostname: 127.0.0.1
secondary_hostname_language: en
base_hostname: ""
secondary_base_hostname: ""

drupal_editor_rolename: editor
drupal_publisher_rolename: publisher
drupal_ckan_admin_rolename: ckan_admin

admin: {'username' : 'admin', 'password': 'admin', 'email': 'vagrant@localhost'}

harvest_user: {'username' : 'harvest', 'password': 'harvest', 'email': 'harvest@localhost'}

ytp_users:
  - username: 'test-editor'
    password: 'test-editor'
    email: 'editor@localhost'
  - username: 'test-publisher'
    password: 'test-publisher'
    email: 'publisher@localhost'

drupal_roles:
  - { 'username': "{{ admin.username }}", 'role': "{{ drupal_ckan_admin_rolename }}" }
  - { 'username': "test-editor", 'role': "{{ drupal_editor_rolename }}" }
  - { 'username': "test-editor", 'role': "{{ drupal_ckan_admin_rolename }}" }
  - { 'username': "test-publisher", 'role': "{{ drupal_publisher_rolename }}" }

ckan_admins:
  - "{{ admin.username }}"
  - "{{ harvest_user.username }}"
  - "test-editor"

ckan_ini: /etc/ckan/default/production.ini
virtual_environment: /usr/lib/ckan/default
datapusherenv: /usr/lib/ckan/datapusher
ckan_who_ini: /etc/ckan/default/who.ini

harvest_sources: false

ckan_version: "2.8.1"
ckan_branch: "ckan-{{ ckan_version }}"

email_domain: "{{ hostname }}"
email_from: "no-reply@{{ email_domain }}"
error_email_from: "error@{{ email_domain }}"

admin_email: vagrant@localhost
error_email: "{{ admin_email }}"
client_email: vagrant@localhost

#smtp_server key is required by the external ckan mailer component
smtp_server_domain: "{{ smtp.server_domain }}"

google_analytics: false
# enable: google_analytics: { 'id': "", 'account': "", 'username': "", 'password': "", 'type': "" }
certificates_path: "/etc/ssl/opendata"

basic_auth_path: false
nfs_shared_path: "/srv/ytp/shared"
local_cache: "/tmp/ytp/cache"

import_base_organizations: false
import_finto_tags: false

recaptcha_public_key: "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
recaptcha_private_key: "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"

Reindex: false

show_postit_demo: true


postgres:
  users:
    ckan:
      username: ckan_default
      password: "{{ secret.database_ckan_password }}"
    ckan_datastore:
      username: datastore_default
      password: "{{ secret.database_ckan_datastore_password }}"
    drupal:
      username: drupal
      password: "{{ secret.database_drupal_password }}"
    drupal8:
      username: drupal8
      password: "{{ secret.database_drupal8_password }}"

  server:
    installed_locally: "{{ postgres_conf.installed_locally }}"
    host: "{{ postgres_conf.host }}"
    port: 5432
    admin_user: "{{ postgres_conf.admin_user }}"
    admin_password: "{{ postgres_conf.admin_password }}"
    trusted_ip_range: 10.0.0.0/8
  databases:
    ckan:
      name: ckan_default
      owner: ckan_default
    ckan_datastore:
      name: datastore_default
      owner: ckan_default
    drupal:
      name: drupal
      owner: drupal
    drupal8:
          name: drupal8
          owner: drupal8

drupal:
  hash_salt: "{{ secret.drupal_hash_salt }}"

postgres_conf:
  installed_locally: true
  host: 127.0.0.1
  admin_user: postgres
  admin_password:


secret:
  database_ckan_password: pass
  database_ckan_datastore_password: pass
  database_drupal_password: pass
  database_drupal8_password: pass
  drupal_hash_salt: IzqME5cJk_x1ZV7oO3UXtHnM7p8R-mLVU5ZiKPWbzDQ
  smtp_user: username
  smtp_password: password

rds_domain_common_part: cnb7uthj3tqq.eu-west-1.rds.amazonaws.com


AWS:
  enabled: false
  region: S3_EU_WEST
  use_iam_role: false
  access_key: somekey
  secret_access_key: somesecret
  ckan_s3_bucket: somebucket
  smtp_server_domain: "email-smtp.eu-west-1.amazonaws.com"

debug_enabled: false

