---

# Database hostname is the first database under dbserver group in Ansible inventory file
database_host: "{{ hostvars[groups['dbserver'][0]]['inventory_hostname'] }}"
# Database is expected to be in the same subnet as the webservers
database_ip_range: "{% if vagrant is defined %}10.0.0.0/8{% else %}172.16.0.0/12{% endif %}"
database_port: 5432

solr_host: "{{ database_host }}"
solr_port: "8983"

redis_hostname: "{{ database_host }}"
redis_port: "6379"

ckan_database_name: ckan_default
ckan_database_username: ckan_default
ckan_database_password: pass
ckan_database_host: "{{ database_host }}"

ckan_test_database: { 'name': "ckan_test", 'username': "{{ ckan_database_username }}" }

datastore_database_name: datastore_default
datastore_database_username: datastore_database_default
datastore_database_password: pass
datastore_username: datastore_default
datastore_password: pass
datastore_database_host: "{{ database_host }}"

drupal_database_name: drupal
drupal_database_username: drupal
drupal_database_password: drupal

www_root: /var/www
www_user: www-data
www_group: www-data

drupal_name: ytp

server_path: /srv/ytp
cache_path: "{{ server_path }}/cache"
backup_path: "{{ server_path }}/backup"
scripts_path: "{{ server_path }}/scripts"
log_path: /var/log/ckan
static_path: "{{ www_root }}/static"

files_root: "{{ server_path }}/files"

all_paths:
  - "{{ server_path }}"
  - "{{ cache_path }}"
  - "{{ backup_path }}"
  - "{{ scripts_path }}"
  - "{{ log_path }}"
  - "{{ static_path }}"

hostname: "{{ inventory_hostname }}"
hostname_language: fi
secondary_hostname: 127.0.0.1
secondary_hostname_language: en
base_hostname: ""
secondary_base_hostname: ""

drupal_editor_rolename: editor
drupal_publisher_rolename: publisher
drupal_ckan_admin_rolename: ckan_admin

admin: {'username' : 'admin', 'password': 'admin', 'email': 'vagrant@localhost'}

harvest_user: {'username' : 'harvest', 'password': 'harvest', 'email': 'harvest@localhost'}

ytp_users:
  - username: 'test-editor'
    password: 'test-editor'
    email: 'editor@localhost'
  - username: 'test-publisher'
    password: 'test-publisher'
    email: 'publisher@localhost'

drupal_roles:
  - { 'username': "{{ admin.username }}", 'role': "{{ drupal_ckan_admin_rolename }}" }
  - { 'username': "test-editor", 'role': "{{ drupal_editor_rolename }}" }
  - { 'username': "test-editor", 'role': "{{ drupal_ckan_admin_rolename }}" }
  - { 'username': "test-publisher", 'role': "{{ drupal_publisher_rolename }}" }

ckan_admins:
  - "{{ admin.username }}"
  - "{{ harvest_user.username }}"
  - "test-editor"

ckan_ini: /etc/ckan/default/production.ini
virtual_environment: /usr/lib/ckan/default

harvest_sources: false

ckan_version: "2.3"

email_domain: "localhost"
email_domain_access: "localhost"
email_from: "no-reply@{{ email_domain }}"
error_email_from: "error@{{ email_domain }}"

admin_email: vagrant@localhost
error_email: "{{ admin_email }}"
client_email: vagrant@localhost

google_analytics: false
# enable: google_analytics: { 'id': "", 'account': "", 'username': "", 'password': "", 'type': "" }
certificates_path: "/etc/ssl/opendata"

basic_auth_path: false
nfs_shared_path: "/srv/ytp/shared"
local_cache: "/tmp/ytp/cache"

import_base_organizations: false
import_finto_tags: false

recaptcha_public_key: "6Lcq_vsSAAAAAAQfNLinsdOD0JbGLbOzZqRlavlB"
recaptcha_private_key: "6Lcq_vsSAAAAADKfbYWkYGV53s2_4UWyuVpMP89X"
