---

modules:
  - ytp-assets-common
  - ckanext-drupal7
  - ckanext-ytp-drupal
  - ckanext-ytp-tasks
  - ckanext-ytp-request
  - ckanext-ytp-main
  - ckanext-hierarchy
  - ckanext-googleanalytics
  - ckanext-ytp-comments
  - ytp-theme-drupal
  - ytp-drupal-user
  - ckanext-qa
  - ckanext-archiver
  - ckanext-harvest
  - ckanext-spatial
  - ckanext-report
  - ckanext-datarequests
  - ckanext-dcat


modules_path: ../modules

clear_module_cache: false
