protected_forms:
  allowed_scripts:
    - Latin
  check_quantity: 50
  reject_message: 'Oops! It looks like your post contains spam content. If you believe otherwise, please contact us. We apologize for the inconvenience.'
  reject_patterns: "http://, https://, ftp://, mailto:, smb://, afp://, file://, gopher://, news://, ssl://, sslv2://, sslv3://, tls://, tcp://, udp://\r\nsex, porn, fuck, free, win, captcha, spam, www"
  log_rejected: 0
  langcode: en