---

- name: Set PHP pathinfo
  ini_file:
    dest: "{{ php_fpm_ini_file }}"
    section: PHP
    option: cgi.fix_pathinfo
    value: "0"
  notify: restart php-fmp service

- name: Set PHP upload_max_filesize
  ini_file:
    dest: "{{ php_fpm_ini_file }}"
    section: PHP
    option: upload_max_filesize
    value: "10M"
  notify: restart php-fmp service

- name: Set PHP session samesite flag
  ini_file:
    dest: "{{ php_fpm_ini_file }}"
    section: Session
      option: session.cookie_samesite
      value: "Lax"
  notify: restart php-fmp service

- name: Set socket to listen
  ini_file:
    dest: "{{ php_fpm_config_file }}"
    section: www
    option: listen
    value: /tmp/phpfpm.socket
  notify: restart php-fmp service

- name: Set socket listen owner
  ini_file:
    dest: "{{ php_fpm_config_file }}"
    section: www
    option: listen.owner
    value: "{{ php_www_user }}"
  notify: restart php-fmp service

- name: Set socket listen group
  ini_file:
    dest: "{{ php_fpm_config_file }}"
    section: www
    option: listen.group
    value: "{{ php_www_group }}"
  notify: restart php-fmp service

- name: Set socket listen mode
  ini_file:
    dest: "{{ php_fpm_config_file }}"
    section: www
    option: listen.mode
    value: "0660"
  notify: restart php-fmp service

- name: Configure pm.max_children setting
  ini_file:
    dest: "{{ php_fpm_config_file }}"
    section: www
    option: pm.max_children
    value: "{{ php_max_children }}"
  notify: restart php-fmp service

- name: Configure pm.start_servers setting
  ini_file:
    dest: "{{ php_fpm_config_file }}"
    section: www
    option: pm.start_servers
    value: "{{ php_start_servers }}"
  notify: restart php-fmp service

- name: Configure pm.max_spare_servers setting
  ini_file:
    dest: "{{ php_fpm_config_file }}"
    section: www
    option: pm.max_spare_servers
    value: "{{ php_max_spare_servers }}"
  notify: restart php-fmp service

- name: Configure pm.min_spare_servers setting
  ini_file:
    dest: "{{ php_fpm_config_file }}"
    section: www
    option: pm.min_spare_servers
    value: "{{ php_min_spare_servers }}"
  notify: restart php-fmp service
