# Launch AWS EC2 instances, test ansible roles and terminate instances

- name: Play 1 - Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    aws_private_key_name: "{{ lookup('env','AWS_PRIVATE_KEY_NAME') }}"
    aws_ec2_instance_type: "{{ lookup('env','AWS_EC2_INSTANCE_TYPE') }}"
    aws_ec2_security_group:  "{{ lookup('env','AWS_EC2_SECURITY_GROUP') }}"
    aws_ec2_image: "{{ lookup('env','AWS_EC2_IMAGE') }}"
    aws_region: "{{ lookup('env','AWS_REGION') }}"
    aws_vpc_subnet_id: "{{ lookup('env','AWS_VPC_SUBNET_ID') }}"
    aws_ec2_assign_public_ip: "{{ lookup('env','AWS_EC2_ASSIGN_PUBLIC_IP') }}"
    aws_ec2_instance_profile: "{{ lookup('env','AWS_EC2_INSTANCE_PROFILE') }}"

  tasks:

    - name: Configure local .ssh directory permissions
      file:
        path: ~/.ssh
        state: directory
        mode: 0700

    - name: Configure AWS private key permissions
      file:
        path: ~/.ssh/id_rsa
        mode: 0600

    - name: Disable host key checking
      copy:
        dest: ~/.ssh/config
        content: |
          Host *
              StrictHostKeyChecking no
              IdentityFile ~/.ssh/id_rsa

    - name: Launch EC2 instance
      ec2:
         key_name: "{{ aws_private_key_name }}"
         group: "{{ aws_ec2_security_group }}"
         instance_type: "{{ aws_ec2_instance_type }}"
         image: "{{ aws_ec2_image }}"
         wait: true
         region: "{{ aws_region }}"
         vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
         assign_public_ip: "{{ aws_ec2_assign_public_ip }}"
         instance_profile_name: "{{ aws_ec2_instance_profile }}"
      register: ec2

    - name: Add new EC2 instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: circleci
      with_items: "{{ ec2.instances }}"

    - name: Save instance ids to file
      copy:
        dest: /tmp/instance_ids
        content: "{{ ec2.instance_ids }}"

    - name: Wait for connection
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        delay: 10
        timeout: 300
      with_items: "{{ ec2.instances }}"

- name: Play 2 - Prepare instance(s)
  hosts: circleci
  remote_user: "{{ lookup('env','AWS_EC2_USER') }}"
  become: True
  gather_facts: False

  tasks:

  - name: Block for required packages
    block:
    # Raw module required to check if python exists and install if missing
    - name: Install python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python)
      args:
        warn: False

    - name: Install required packages
      apt:
        name:
          - libssl-dev
          - libffi-dev
          - python-dev
          - python-pip
          - git
          - nfs-common
          - rsync
        update_cache: yes

    - name: Install python packages
      pip:
        name:
          - setuptools
          - awscli
          - ansible
          - markupsafe
        state: latest
    # Sometimes python package is not found right after instance is creataed,
    # retrying seems to solve this issue.
    rescue:
    - name: Install python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python)
      args:
        warn: False

    - name: Install required packages
      apt:
        name:
          - libssl-dev
          - libffi-dev
          - python-dev
          - python-pip
          - git
          - nfs-common
          - rsync
        update_cache: yes

    - name: Install python packages
      pip:
        name:
          - setuptools
          - awscli
          - ansible
          - markupsafe
        state: latest

- name: Play 3 - Configure instance(s)
  hosts: circleci
  remote_user: "{{ lookup('env','AWS_EC2_USER') }}"
  become: True
  gather_facts: True
  vars:
    vagrant: false
    secrets_file_path: does_not_exist
    deployment_environment_id: build_test
    disqus_name: ""
    ssl_path: /etc/ssl
    database_host: "127.0.0.1"
    solr_host: "127.0.0.1"
    database_ip_range: "127.0.0.1/8"
  vars_files:
    - "vars/common.yml"
    - ["vars/environment-specific/{{ deployment_environment_id }}.yml", "vars/none.yml"]
    - ["{{ secrets_file_path }}", "vars/none.yml"]
    - ["vars/local.yml", "vars/none.yml"]

  tasks:

  - name: Set pass_status to default value
    set_fact:
      pass_status: True
      failed_task_name: ""
      failed_task_result: ""

  - name: Block for testing roles
    block:
      - import_role:
          name: common
      - import_role:
          name: users
      - import_role:
          name: clean
      - import_role:
          name: database
      - import_role:
          name: common_webserver
      - import_role:
          name: ssl
      - import_role:
          name: nginx
      - import_role:
          name: postfix
      - import_role:
          name: jetty
      - import_role:
          name: redis
      - import_role:
          name: ckan-extensions
      - import_role:
          name: ckan
      - import_role:
          name: ckan-config
      - import_role:
          name: ckan-database
      - import_role:
          name: ckan-data
      - import_role:
          name: ckan-restart
      - import_role:
          name: drupal
      - import_role:
          name: clamav
      - import_role:
          name: data
      - import_role:
          name: datapusher

    rescue:
    - name: Continue playbook execution to next play always
      command: /bin/true
    - name: Set fact
      set_fact:
        pass_status: False
    - name: Save failed task name
      set_fact:
        failed_task_name: "{{ ansible_failed_task }}"
      when: ansible_failed_task is defined

    - name: Save failed result
      set_fact:
        failed_task_result: "{{ ansible_failed_result }}"
      when: ansible_failed_result is defined

- name: Play 4 - Terminate EC2 instances
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    aws_region: "{{ lookup('env','AWS_REGION') }}"

  tasks:
    - name: Terminate EC2 instances that were previously launched
      ec2:
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'
        region: "{{ aws_region }}"

    - name: Set pass status fact based on previous play
      set_fact:
        pass_status: "{{ hostvars[ ec2.instances[0].public_ip ]['pass_status'] }}"

    - name: Print failed task debug information
      debug:
        msg:
        - "{{ hostvars[ ec2.instances[0].public_ip ]['failed_task_name'] }}"
        - "{{ hostvars[ ec2.instances[0].public_ip ]['failed_task_result'] }}"
        verbosity: 1

    - name: Check actual playbook execution result
      debug:
        msg:
        - "Playbook execution successful: {{ pass_status }}"

      failed_when: pass_status == False
