---

project_root: "{{ playbook_dir }}/.."
base_hostname: "avoindata.fi"
secondary_base_hostname: "opendata.fi"
virtual_environment: /usr/lib/ckan/default

email_domain: "{{ hostname }}"
email_from: "no-reply@{{ email_domain }}"
error_email_from: "error@{{ email_domain }}"

recaptcha_public_key: "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
recaptcha_private_key: "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"

admin:
  username: 'admin'
  password: 'administrator'
  email: 'vagrant@localhost'

ytp_users:
  - username: 'test-editor'
    password: 'test-editor'
    email: 'editor@localhost'
  - username: 'test-publisher'
    password: 'test-publisher'
    email: 'publisher@localhost'
  - username: 'test-user'
    password: 'test-user'
    email: 'user@localhost'

matomo_analytics: false

database_ckan_password: pass
database_ckan_datastore_password: pass
database_drupal8_password: pass
smtp_user: username
smtp_password: password

AWS:
  enabled: false
  region: S3_EU_WEST
  use_iam_role: false
  access_key: somekey
  secret_access_key: somesecret
  ckan_s3_bucket: somebucket
  smtp_server_domain: "email-smtp.eu-west-1.amazonaws.com"
