ckan_hostname: "{{ hostname }}"
ckan_secondary_hostname: "{{ secondary_hostname }}"
ckan_virtual_environment: "{{ virtual_environment }}"
ckan_port: 5000

ckan_debug_enabled: false
ckan_postgres_installed_locally: false
ckan_profiling_enabled: false
ckan_smtp_use_tls: True
ckan_smtp_username: "{{ smtp_user }}"
ckan_smtp_password: "{{ smtp_password }}"
ckan_smtp_server_domain: "{{ smtp_server_domain }}"
ckan_enable_cloudstorage: false
ckan_site_protocol: https
ckan_extension_archiver_cache_protocol: https
ckan_cloudstorage_driver: "{{ AWS.region }}"
ckan_cloudstorage_bucket: "{{ AWS.ckan_s3_bucket }}"
ckan_cloudstorage_local_access: False
ckan_disqus_name: "{{ disqus_name }}"
ckan_recaptcha_public_key: "{{ recaptcha_public_key }}"
ckan_recaptcha_private_key: "{{ recaptcha_private_key }}"

ckan_postgres:
  users:
    ckan:
      username: ckan_default
      password: pass
    ckan_datastore:
      username: datastore_default
      password: pass
    drupal8:
      username: drupal8
      password: pass
  server:
    host: 127.0.0.1
  databases:
    ckan:
      name: ckan_default
      owner: ckan_default
    ckan_datastore:
      name: datastore_default
      owner: ckan_default
    drupal8:
      name: drupal8
      owner: drupal8

ckan_admins:
  - "{{ admin.username }}"


ckan_matomo_analytics: "{{ matomo_analytics }}"

ckan_show_postit_demo: false
