---

ckan_package: python-ckan_{{ ckan_version }}_amd64.deb

harvester_user: "{{ www_user }}"
celery_user: "{{ www_user }}"

ckan_plugins_default: stats
# order matters, when templates call super()
ckan_plugins: multilingual_dataset harvest ckan_harvester hri_harvester dcat dcat_rdf_harvester dcat_json_harvester dcat_json_interface spatial_metadata spatial_query csw_harvester drupal7 datarequests report qa archiver ytp_organizations ytp_comments ytp_request hierarchy_display ytp_theme ytp_drupal ytp_tasks ytp_dataset ytp_user ytp_service datastore

ckan_extensions:
  - ckanext-drupal7
  - ckanext-ytp-drupal
  - ckanext-ytp-tasks
  - ckanext-ytp-request
  - ckanext-ytp-main
  - ckanext-hierarchy
  - ckanext-googleanalytics
  - ckanext-ytp-comments
  - ckanext-qa
  - ckanext-datarequests
  - ckanext-harvest
  - ckanext-archiver
  - ckanext-spatial
  - ckanext-report
  - ckanext-dcat

redis_harvest_database: 0
redis_celery_database: 1

supervisor_services:
  - ckan_gather_consumer
  - ckan_fetch_consumer
  - celery_celery
  - celery_bulk
  - celery_priority
  - celerybeat

# Override these on servers! 
baker_session_secret: "9PBdkxokLGWW4M4jeTI25h+4t"
app_instance_uuid: "{dc6259b8-f112-4d23-8816-aadcede1895c}"

ckan_files_path: "{{ files_root }}/ckan"
ckan_max_resource_size: 150
translation_cache_path: "{{ cache_path }}/translations"
translation_languages:
  - "fi"
  - "sv"

translation_projects:
  - "ckanext-drupal7"
  - "ckanext-ytp-request"
  - "ckanext-ytp-drupal"
  - "ytp-assets-common"
  - "ckanext-ytp-main"
  - "ckanext-ytp-comments"
  - "ckanext-qa"
  - "ckanext-datarequests"
  - "ckanext-spatial"

ckan_site_id: "default"

patches_cache_path: "{{ cache_path }}/patch"
ckan_source_path: "{{ virtual_environment }}/src/ckan"
spatial_source_path: "{{ virtual_environment }}/src/ckanext-spatial"

ckan_patches:
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/e7936fe8707a847387661248b5b0d9d3ddc526ae.patch", file: "fix_hardcoded_languages.patch" } # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/4d596cca05a55fdcba9fbc2af1ecaf46b843b737.patch", file: "fix_invalid_date_indexing.patch" } # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/7367b56bc023da854aa31e05ff63ef8307c06f41.patch", file: "fix_multilingual_search.patch" } # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/9e80b58f24dea9d93ec84aac258f5436dfcfdd9c.patch", file: "fix_collection_type_translation.patch" } # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/cbbca2047c68c377ef9408fc4df157b1acb1b02c.patch", file: "usability-fix-for-image-upload.patch" } # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/8f7ec3f9fb6a35bb4a7e52784920ed99b7c7e245.patch", file: "fix-double-encoding-in-autocomplete.patch"} # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/cde3c21a8b8612b88ef61b47488465b2926a6840.patch", file: "fix-template-error-in-resources.patch"} # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/eb59ffde3a702077ffbc8de8e3ff425b29974d6c.patch", file: "add-event-callbacks-to-autocomplete.patch"} # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/9497130896c969982a3b8b5e9685295428fd7d2b.patch", file: "enable-url-quoting"} # pullreq in ckan master
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/85ef19c73faa7e841e9e0b94ec1044dbb6fee389.patch", file: "enable-celery-queues"} # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/34382a3ff1cb0d16f31e9e00955a3feabbdd64f5.patch", file: "remove-main-debug-css"} # ytp specific
  - { patch: "https://github.com/yhteentoimivuuspalvelut/ckan/commit/0c973510ab7b77ac20e375cd263661eb190eaba5.patch", file: "remove-old-rdf-templates"} # ytp specific

service_database_enabled: false
auto_author_enabled: true
