---

- name: Create Drupal installation directories if they don't exist
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ drupal_user }}"
    group: "{{ drupal_group }}"
    mode: 0755
  with_items:
    - "/var/www/.composer"  # Required for composer cache
    - "{{ drupal_root }}"
    - "{{ drupal_root }}/site_config"

- name: Synchronize drupal8 project
  synchronize:
    src: drupal8/
    dest: "{{ drupal_root }}/"

- name: Ensure drupal root ownership
  file:
    path: "{{ drupal_root }}"
    owner: "{{ drupal_user }}"
    group: "{{ drupal_group }}"
    mode: 0755
    recurse: true
    follow: false

- name: Ensure Drupal sync directory exists
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755
  with_items:
    - "{{ drupal_root }}/config"
    - "{{ drupal_root }}/config/sync"

- name: Remove composer lock file if it exists
  file:
    path: "{{ drupal_root }}/composer.lock"
    state: absent

- name: Install Drupal dependencies
  become: true
  become_user: "{{ drupal_user }}"
  composer:
    command: install
    working_dir: "{{ drupal_root }}"


- name: Ensure drupal public files directory exists
  file:
    path: "{{ drupal_public_files_directory }}"
    state: directory
    owner: "{{ drupal_user }}"
    group: "{{ drupal_group }}"
    mode: 0755

- name: Create sub directories for public files directory
  file:
    path: "{{ drupal_public_files_directory }}/{{ item }}"
    state: directory
    owner: "{{ drupal_user }}"
    group: "{{ drupal_group }}"
    mode: 0755
  with_items: "{{ drupal_public_files_directory_subdirs }}"

- name: Ensure correct permission for public files directory
  file:
    path: "{{ drupal_public_files_directory }}"
    recurse: true
    owner: "{{ drupal_user }}"
    group: "{{ drupal_group }}"

- name: Create .htaccess file for public files directory
  template:
    src: public_files_dir_htaccess.j2
    dest: "{{ drupal_public_files_directory }}/.htaccess"
    owner: root
    group: root
    mode: 0644

- name: Check default public files path status
  stat:
    path: "{{ drupal_root }}/web/sites/default/files"
  register: drupal_default_public_files_path

- name: Remove default public files directory
  file:
    path: "{{ drupal_root }}/web/sites/default/files"
    state: absent
  when: drupal_default_public_files_path.stat.isdir

- name: Link default public files path to target directory
  file:
    path: "{{ drupal_root }}/web/sites/default/files"
    state: link
    src: "{{ drupal_public_files_directory }}"

- name: Synchronize custom modules
  synchronize:
    src: "{{ drupal_modules_path }}/{{ item.src_name }}/"
    dest: "{{ drupal_root }}/web/modules/{{ item.module_name }}"
  when: drupal_deployment_environment_id != "vagrant"
  with_items: "{{ drupal_custom_modules }}"

- name: Symlink custom modules
  file:
    state: link
    src: "/vagrant/modules/{{ item.src_name }}/"
    dest: "{{ drupal_root }}/web/modules/{{ item.module_name }}"
  when: drupal_deployment_environment_id == "vagrant"
  with_items: "{{ drupal_custom_modules }}"

- name: Copy Drupal services yml
  template:
    src: "services.yml.j2"
    dest: "{{ drupal_root }}/web/sites/default/services.yml"

- name: Deploy robots.txt
  copy:
    src: "{{ drupal_search_engine_robots_filename }}"
    dest: "{{ drupal_root }}/web/robots.txt"

- name: Configure drupal instance
  include_tasks: configure_drupal.yml
  when: drupal_configure_instance
