---

- name: Download Drupal themes
  command: drush dl -y "{{ item }}" chdir="{{ drupal_root }}" creates="{{ drupal_root }}/sites/all/themes/{{ item }}/"
  register: download_themes
  with_items:
    - bootstrap-7.x-3.10
  tags:
  - drupal

- name: Enable Drupal themes
  command: drush en -y "{{ item }}" chdir="{{ drupal_root }}"
  when: download_themes|changed
  with_items:
    - bootstrap
  tags:
  - drupal

- name: Install YTP Drupal theme
  shell: rm -rf "{{ drupal_theme_path }}/ytp_theme" && cp -r "{{ cache_path }}/ytp-theme-drupal" "{{ drupal_theme_path }}/ytp_theme"
  tags:
  - drupal

- name: Create vendor js directory
  file: path="{{ drupal_theme_path }}/ytp_theme/vendor" state=directory
  tags:
    - drupal

- name: Symlink ytp bootstrap css
  command: ln -sf "/var/www/resources/vendor/{{ item }}" "{{ drupal_theme_path }}/ytp_theme/vendor/{{ item }}"
  with_items:
    - bootstrap.min.css
  tags:
    - drupal


- name: Symlink vendor js to drupal
  command: ln -sf "/var/www/resources/vendor/{{ item }}" "{{ drupal_theme_path }}/ytp_theme/vendor/{{ item }}"
  with_items:
    - moment-with-locales.js
    - bootstrap-datetimepicker.js
    - bootstrap.min.js
  tags:
    - drupal

- name: Symlink vendor fonts to drupal
  command: ln -s "/var/www/resources/fonts/" "{{ drupal_theme_path }}/ytp_theme/fonts"
  tags:
    - drupal


- name: Enable YTP theme
  command: drush en -y ytp_theme chdir="{{ drupal_root }}"
  tags:
  - drupal
