name: Restart Prod containers

on:
  workflow_dispatch:

jobs:
  restart-prod:
    name: restart prod containers
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
    strategy:
      matrix:
        container: ["ckan", "ckanCron", "drupal"]
    steps:
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: github-actions
          aws-region: eu-west-1

      - name: Restart containers
        run: |
          aws ecs update-service --cluster ${{ secrets.prod_cluster }} --service ${{ matrix.container }} --force-new-deployment
